on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build $GITHUB_WORKSPACE/build --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{ matrix.os }}
          path: ${{ github.workspace }}/build
