on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for Linux x64

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S ${{ github.workspace }} -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - uses: actions/upload-artifact@v4
        with:
          name: libsharpspades.so
          path: build/libsharpspades.so
